backends:
- mysql:
  kind: mysql
  env:
    user: sysrun
    password: sysrun
    dbnme: db1
- postgres:
  kind: postgres
  env:
    user: sysrun
    password: sysrun
    dbname: db1	
    host: localhost
